services:
  - type: web
    name: portfolio-guru
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: FERNET_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///./portfolio_guru.db
